---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nex-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nex-nginx
  template:
    metadata:
      labels:
        app: nex-nginx
    spec:
      containers:
        - name: nex-nginx
          image: poolziee/nexusmeals-ingress:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: nex-nginx
spec:
  selector:
    app: nex-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
