name: push

on:
  push:
    branches:
      - "master"

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: poolziee/nexusmeals-ingress:latest
  deploy_to_aks:
    runs-on: ubuntu-latest
    needs: build_and_push_docker
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: "${{ secrets.resource_group }}"
          cluster-name: "${{ secrets.cluster_name }}"

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: "default"
          manifests: |
            nex-nginx.yml
          images: poolziee/nexusmeals-ingress:latest
          pull-images: true
